module.exports = {
  admins: "admins",
  adminTypes: "adminTypes",
  users: "users",
  userLogs: "userLogs",
  settings: "settings",
  domains: "domains",
  subdomains: "subdomains",
  questions: "questions",
  assessments: "assessments",
  policies: "policies",
  initiatives: "initiatives",
  countries: "countries",
  intergovernmentalOrganisations: "intergovernmentalOrganisations",
  initiativeTypes: "initiativeTypes",
  aiPrinciples: "aiPrinciples",
  aiTags: "aiTags",
};
